[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Redirections pour les routes API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirections pour les pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

